<?php
/**
 * Form Generator Class
 *
 * AI-powered ACF field group generation
 *
 * @package IgnisAI
 */

// Exit if accessed directly
if ( ! defined( 'ABSPATH' ) ) {
    exit;
}

/**
 * Form Generator class
 */
class IgnisAI_Form_Generator {

    /**
     * AI Client instance
     *
     * @var IgnisAI_Client
     */
    private $ai_client;

    /**
     * Constructor
     */
    public function __construct() {
        $this->ai_client = new IgnisAI_Client();
    }

    /**
     * Generate ACF field group from description
     *
     * @param string $description Description of the desired fields
     * @param string $post_type Post type to attach fields to
     * @param string $group_title Field group title
     * @return array|WP_Error Field group array or error
     */
    public function generate_field_group( $description, $post_type = 'post', $group_title = '' ) {
        if ( empty( $group_title ) ) {
            $group_title = 'AI Generated Fields';
        }

        $prompt = $this->build_field_group_prompt( $description, $post_type, $group_title );

        $response = $this->ai_client->generate_text( $prompt, array(
            'max_tokens' => 2000,
            'temperature' => 0.3, // Lower temperature for more consistent JSON
        ));

        if ( is_wp_error( $response ) ) {
            return $response;
        }

        // Parse JSON response
        $field_group = $this->parse_field_group_response( $response );

        if ( is_wp_error( $field_group ) ) {
            return $field_group;
        }

        // Add location rules
        $field_group['location'] = array(
            array(
                array(
                    'param' => 'post_type',
                    'operator' => '==',
                    'value' => $post_type,
                ),
            ),
        );

        // Add settings
        $field_group['position'] = 'normal';
        $field_group['style'] = 'default';
        $field_group['label_placement'] = 'top';
        $field_group['instruction_placement'] = 'label';
        $field_group['hide_on_screen'] = '';
        $field_group['active'] = true;
        $field_group['description'] = 'Generated by IgnisAI: ' . $description;

        return $field_group;
    }

    /**
     * Build prompt for field group generation
     *
     * @param string $description User description
     * @param string $post_type Post type
     * @param string $group_title Group title
     * @return string Prompt
     */
    private function build_field_group_prompt( $description, $post_type, $group_title ) {
        $prompt = "Generate an ACF (Advanced Custom Fields) field group configuration based on this description:\n\n";
        $prompt .= $description . "\n\n";
        $prompt .= "Requirements:\n";
        $prompt .= "- Post Type: {$post_type}\n";
        $prompt .= "- Field Group Title: {$group_title}\n\n";

        $prompt .= "Generate a JSON object with this structure:\n";
        $prompt .= "{\n";
        $prompt .= "  \"key\": \"group_xxxxx\",\n";
        $prompt .= "  \"title\": \"{$group_title}\",\n";
        $prompt .= "  \"fields\": [\n";
        $prompt .= "    {\n";
        $prompt .= "      \"key\": \"field_xxxxx\",\n";
        $prompt .= "      \"label\": \"Field Label\",\n";
        $prompt .= "      \"name\": \"field_name\",\n";
        $prompt .= "      \"type\": \"text|textarea|number|email|url|select|checkbox|radio|image|file|wysiwyg|date_picker|...\",\n";
        $prompt .= "      \"instructions\": \"Helper text for the field\",\n";
        $prompt .= "      \"required\": 0,\n";
        $prompt .= "      \"default_value\": \"\",\n";
        $prompt .= "      \"placeholder\": \"\"\n";
        $prompt .= "    }\n";
        $prompt .= "  ]\n";
        $prompt .= "}\n\n";

        $prompt .= "Guidelines:\n";
        $prompt .= "- Use appropriate field types for the data\n";
        $prompt .= "- Use snake_case for field names\n";
        $prompt .= "- Add helpful instructions for each field\n";
        $prompt .= "- Set required fields appropriately\n";
        $prompt .= "- For select/radio/checkbox fields, include 'choices' as an object\n";
        $prompt .= "- Generate unique keys using format: group_xxxxx and field_xxxxx where xxxxx is random\n\n";

        $prompt .= "Common ACF field types to use:\n";
        $prompt .= "- text, textarea, wysiwyg (for text content)\n";
        $prompt .= "- number (for numeric values)\n";
        $prompt .= "- email, url (for specific formats)\n";
        $prompt .= "- select, checkbox, radio (for choices)\n";
        $prompt .= "- true_false (for yes/no)\n";
        $prompt .= "- date_picker, date_time_picker (for dates)\n";
        $prompt .= "- image, file, gallery (for media)\n";
        $prompt .= "- relationship, post_object (for post connections)\n\n";

        $prompt .= "Return ONLY the JSON object, no additional text or formatting.";

        return $prompt;
    }

    /**
     * Parse field group response from AI
     *
     * @param string $response AI response
     * @return array|WP_Error Parsed field group or error
     */
    private function parse_field_group_response( $response ) {
        // Try to extract JSON from response
        $response = trim( $response );

        // Remove markdown code blocks if present
        $response = preg_replace( '/^```json\s*\n?/', '', $response );
        $response = preg_replace( '/\n?```$/', '', $response );
        $response = trim( $response );

        $field_group = json_decode( $response, true );

        if ( json_last_error() !== JSON_ERROR_NONE ) {
            return new WP_Error(
                'json_parse_error',
                sprintf(
                    /* translators: %s: JSON error message */
                    __( 'Failed to parse field group JSON: %s', 'ignis-ai' ),
                    json_last_error_msg()
                )
            );
        }

        // Validate required fields
        if ( ! isset( $field_group['title'] ) || ! isset( $field_group['fields'] ) ) {
            return new WP_Error(
                'invalid_field_group',
                __( 'Invalid field group structure. Missing required properties.', 'ignis-ai' )
            );
        }

        // Ensure key exists
        if ( ! isset( $field_group['key'] ) ) {
            $field_group['key'] = 'group_' . uniqid();
        }

        // Validate and sanitize fields
        foreach ( $field_group['fields'] as $index => $field ) {
            if ( ! isset( $field['key'] ) ) {
                $field_group['fields'][$index]['key'] = 'field_' . uniqid();
            }
            if ( ! isset( $field['name'] ) ) {
                return new WP_Error(
                    'invalid_field',
                    sprintf(
                        /* translators: %d: Field index */
                        __( 'Field at index %d is missing required "name" property.', 'ignis-ai' ),
                        $index
                    )
                );
            }
            if ( ! isset( $field['type'] ) ) {
                $field_group['fields'][$index]['type'] = 'text'; // Default to text
            }
        }

        return $field_group;
    }

    /**
     * Import field group into ACF
     *
     * @param array $field_group Field group array
     * @return int|WP_Error Field group post ID or error
     */
    public function import_field_group( $field_group ) {
        if ( ! function_exists( 'acf_import_field_group' ) ) {
            return new WP_Error(
                'acf_not_available',
                __( 'ACF is not available. Please install and activate Advanced Custom Fields.', 'ignis-ai' )
            );
        }

        try {
            $result = acf_import_field_group( $field_group );

            if ( ! $result ) {
                return new WP_Error(
                    'import_failed',
                    __( 'Failed to import field group into ACF.', 'ignis-ai' )
                );
            }

            return $result;

        } catch ( Exception $e ) {
            return new WP_Error(
                'import_exception',
                $e->getMessage()
            );
        }
    }
}
